package com.humblesolutions.finai.model

import com.humblesolutions.finai.util.Money
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * One month's budget, from `GET /budgets/{YYYY-MM}` (PRD F4).
 *
 * Generated by the server from what the household actually spent, so nobody
 * has to build one by hand — and overridable line by line, because F4 is
 * explicit that the generated number is a starting point and the person
 * decides.
 *
 * **Every figure here is the server's.** No property below adds, subtracts or
 * totals an amount (CLAUDE.md → Who computes what). The one derived thing is
 * [BudgetLine.fraction], which is a bar's length, not money.
 *
 * Amounts are decimal strings in both directions (PRD §4.4). Defaults on every
 * field, so a payload missing one still decodes — including one from a server
 * that predates this endpoint.
 */
@Serializable
data class Budget(
    val status: BudgetStatus = BudgetStatus.UNKNOWN,

    /**
     * The first day of the month this budget covers.
     *
     * A full date (`2026-10-01`) even though the URL takes `YYYY-MM`: the
     * server names a month by its 1st, as [Dashboard.month] does.
     */
    val month: String = "",

    val currency: String = "",

    /** How far off a first budget the household is; null once it is ready. */
    val learning: LearningProgress? = null,

    /** What the household expects to earn, from the setup wizard. */
    @SerialName("expected_income")
    val expectedIncome: String = "0",

    /**
     * The spending lines, one per category.
     *
     * **While learning this is not empty** — it holds the lines the person set
     * by hand. Nothing is generated until there is history to generate from,
     * but manual budgeting is available from the first day (PRD F9), so a
     * hand-set line shows whatever the status says.
     */
    val lines: List<BudgetLine> = emptyList(),

    /** Income left after every other line, when positive. Null when there is none. */
    val savings: BudgetLine? = null,

    /** The larger of observed payments and the sum of minimums. Null when there are no debts. */
    val debt: BudgetLine? = null,

    @SerialName("total_allocated")
    val totalAllocated: String = "0",

    @SerialName("total_spent")
    val totalSpent: String = "0",

    /**
     * How far the lines exceed expected income; null when they do not.
     *
     * Worth saying plainly on screen rather than leaving someone to notice:
     * a budget that spends more than it earns is the thing they opened the
     * screen to find out.
     */
    val shortfall: String? = null,

    /** Spending with no category: reported so it is not missing, never budgeted. */
    @SerialName("uncategorised_spent")
    val uncategorisedSpent: String = "0",

    @SerialName("uncategorised_count")
    val uncategorisedCount: Int = 0,
) {
    val symbol: String get() = Money.symbol(currency)

    val fractionDigits: Int get() = Money.fractionDigits(currency)

    /** True once the server has enough history to generate from. */
    val isReady: Boolean get() = status == BudgetStatus.READY

    /** True when the lines exceed expected income. */
    val hasShortfall: Boolean get() = shortfall != null

    /** True when some spending is not filed into any category. */
    val hasUncategorised: Boolean get() = uncategorisedCount > 0

    /**
     * Every line the screen can open an editor for, spending first.
     *
     * [savings] and [debt] are allocations with rules of their own rather
     * than categories someone spends in, so they are listed apart from
     * [lines] — but they are still rows on the screen, and still editable.
     */
    val allLines: List<BudgetLine> get() = lines + listOfNotNull(savings, debt)
}

/** Whether a budget could be generated yet (PRD F8). */
@Serializable(with = BudgetStatusSerializer::class)
enum class BudgetStatus(val wire: String) {
    /** Not enough history yet; [Budget.learning] says how much is missing. */
    LEARNING("learning"),

    /** Generated from real spending. */
    READY("ready"),

    /**
     * A status this build does not know. Read as not ready: showing a budget
     * the server did not call ready would put generated-looking figures in
     * front of someone on the strength of a word we could not interpret.
     */
    UNKNOWN(""),
    ;

    companion object {
        fun fromWire(value: String?): BudgetStatus = entries.firstOrNull { it != UNKNOWN && it.wire == value } ?: UNKNOWN
    }
}

internal object BudgetStatusSerializer :
    WireEnumSerializer<BudgetStatus>("BudgetStatus", { BudgetStatus.fromWire(it) }, { it.wire })

/**
 * How far the household is from its first generated budget (PRD F8).
 *
 * The threshold is the server's and is never recomputed here — [ready] is
 * read, not derived from [completeMonths] and [transactions] against [needs].
 * Those three are for showing progress, not for deciding it.
 */
@Serializable
data class LearningProgress(
    val ready: Boolean = false,

    /** Complete calendar months with countable transactions. */
    @SerialName("complete_months")
    val completeMonths: Int = 0,

    /** Countable transactions in total. */
    val transactions: Int = 0,

    val needs: LearningNeeds = LearningNeeds(),
)

/** What [LearningProgress] is counting toward. */
@Serializable
data class LearningNeeds(
    @SerialName("complete_months")
    val completeMonths: Int = 0,
    val transactions: Int = 0,
)

/**
 * One category's line in a month's budget.
 *
 * [suggested] and [allocated] are separate because they diverge: a line the
 * person set keeps their amount while the suggestion underneath it keeps
 * moving with their spending. Showing both is what makes an override legible
 * — "you chose $500, we'd have said $440" — instead of a number with no story.
 */
@Serializable
data class BudgetLine(
    @SerialName("category_id")
    val categoryId: String = "",

    /** The category's stable slug (`groceries`, `savings`, `debt_payment`). */
    val slug: String = "",

    val name: String = "",

    /** What the server would allocate from the last three months' median. */
    val suggested: String = "0",

    /** What is allocated: [suggested], unless the person set it. */
    val allocated: String = "0",

    /** True when the person set [allocated] by hand; regeneration will not move it. */
    @SerialName("is_user_set")
    val isUserSet: Boolean = false,

    /** This month's countable debits in the category, by the dashboard's rule. */
    val spent: String = "0",

    /**
     * How far spending is past the allocation, as the server worked it out —
     * `"0.00"` within it. Sent on `/dashboard`'s budget only; null from
     * `/budgets`, where [overBy] stands in.
     */
    val over: String? = null,
) {
    /**
     * How far through the allocation this line's spending is, 0 to 1 — the
     * length of its bar and nothing else.
     *
     * **The `Double` here is a ratio, not money.** CLAUDE.md's "never
     * `Double` for money" guards against a figure that rounds; this one is
     * never shown, stored or sent — it is multiplied by a bar's width and
     * thrown away, and a bar is about 300 pixels long. Every amount involved
     * stays a decimal string, and the comparison that decides *over* or
     * *within* is [Money.compare] on the strings, not on these doubles.
     *
     * Clamped at 1 so an overspent bar fills rather than overflowing its
     * track; the overspend is said in words beside it, never left to the bar
     * to convey. An allocation of zero reads as full when anything was spent,
     * because every bit of it is over.
     */
    fun fraction(fractionDigits: Int = 2): Double {
        val allocatedPositive = Money.isPositive(allocated, fractionDigits)
        if (!allocatedPositive) return if (Money.isPositive(spent, fractionDigits)) 1.0 else 0.0
        if (isOver(fractionDigits)) return 1.0
        val spentUnits = Money.normalize(spent, fractionDigits)?.toDoubleOrNull() ?: return 0.0
        val allocatedUnits = Money.normalize(allocated, fractionDigits)?.toDoubleOrNull() ?: return 0.0
        if (allocatedUnits <= 0.0) return 0.0
        return (spentUnits / allocatedUnits).coerceIn(0.0, 1.0)
    }

    /** True when spending has passed the allocation. */
    fun isOver(fractionDigits: Int = 2): Boolean = Money.compare(spent, allocated, fractionDigits) > 0

    /**
     * How far past the allocation, or null when the line is within it.
     *
     * The subtraction is unavoidable — the server sends no `over` field on
     * this endpoint — but it is a difference of two figures it did send, not
     * a figure of our own. [Money.difference] rather than arithmetic, so a
     * currency without cents behaves.
     */
    fun overBy(fractionDigits: Int = 2): String? {
        if (!isOver(fractionDigits)) return null
        return Money.difference(spent, allocated, fractionDigits)
    }

    /** True when the person's amount differs from what the server would suggest. */
    fun differsFromSuggestion(fractionDigits: Int = 2): Boolean = isUserSet && Money.compare(allocated, suggested, fractionDigits) != 0
}
